### ISSUE TITLE
Discrete stochastic analogues of Erlang models

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/shopping-list#17]
[https://doi.org/10.1080/17513758.2017.1401677](https://doi.org/10.1080/17513758.2017.1401677)

**Comment by ghost** [comment]
I am going to implement this in R.

**Comment by ghost** [comment]
Implemented in R and Julia.

**Comment by sdwfrost** [comment]
Added to main repository:

[https://github.com/epirecipes/epicookbook/commit/4760a54aa567dadfd0967b8af94882e32078f69f](https://github.com/epirecipes/epicookbook/commit/4760a54aa567dadfd0967b8af94882e32078f69f)
