### ISSUE TITLE
Models of Ebola

### ISSUE THREAD

**Issue by epichef** [epirecipes/shopping-list#23]

**Comment by ViralVerity** [comment]
Working on Khan 2015 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4347917/) in python, but for now starting with a mass action transmission term!

**Comment by sdwfrost** [comment]
Hi @ViralVerity , are you going to fit the model to with NLS? Also see this paper (in POMP, so not Python-specific):

[http://rspb.royalsocietypublishing.org/content/282/1806/20150347.short](http://rspb.royalsocietypublishing.org/content/282/1806/20150347.short)

**Comment by ViralVerity** [comment]
I will plug in the values that they got for now, but if I look at fitting later on, I will post it here

**Comment by sdwfrost** [comment]
Cumulative cases that @emvolz and I used for our paper here if the mood takes you.

[https://github.com/sdwfrost/ebov-methods-comparison/blob/master/ebov_cs.txt](https://github.com/sdwfrost/ebov-methods-comparison/blob/master/ebov_cs.txt)

**Comment by sdwfrost** [comment]
Added models by @ViralVerity and @twomagpi

[https://github.com/epirecipes/epicookbook/commit/73d8cc6e50d8b3d0bca90514b699a35266db4139](https://github.com/epirecipes/epicookbook/commit/73d8cc6e50d8b3d0bca90514b699a35266db4139)
