### ISSUE TITLE
Estimation of final sizes

### ISSUE THREAD

**Issue by sdwfrost** [epirecipes/shopping-list#35]
Although we are often interested in the dynamics over time, there are also methods that are targeted on determining the final size of epidemics e.g. [doi:10.1016/j.jtbi.2014.11.029](http://dx.doi.org/10.1016/j.jtbi.2014.11.029).

**Comment by sangeetabhatia03** [comment]
I am interested in doing this (starting tomorrow though).

**Comment by sdwfrost** [comment]
Sounds good - in what language?

**Comment by sangeetabhatia03** [comment]
I'll do it in R first and then if there is time, in Julia or Python.

**Comment by sdwfrost** [comment]
Notebook in R included, along with my implementation in Julia, Octave, and Scilab.

[https://github.com/epirecipes/epicookbook/commit/3bc280b56ee1db7a125a3745968c49b0351a0038](https://github.com/epirecipes/epicookbook/commit/3bc280b56ee1db7a125a3745968c49b0351a0038)
