### ISSUE TITLE
Observable: Deterministic SIR with seasonal forcing

### ISSUE THREAD

**Issue by c-lack** [epirecipes/shopping-list#47]
https://beta.observablehq.com/@c-lack/forced-sir

**Comment by sdwfrost** [comment]
Incorporated into a collection, with minor edit for attribution:
[https://beta.observablehq.com/@epichef/forced-sir](https://beta.observablehq.com/@epichef/forced-sir)

Included in the cookbook as an iframe:
[http://epirecip.es/epicookbook/chapters/sirforced/js_observable](http://epirecip.es/epicookbook/chapters/sirforced/js_observable)

**Comment by c-lack** [comment]
I'm having issues viewing this in the cookbook. The plot goes off the right hand side of the screen, and the list of parameters is cut off with no ability to scroll through them.
![capture](https://user-images.githubusercontent.com/28656052/46357007-cb4dd780-c65b-11e8-943c-fac38530b4dd.PNG)
