### ISSUE TITLE
Observable Simple SIS model - js 

### ISSUE THREAD

**Issue by ersouthall** [epirecipes/shopping-list#48]
https://beta.observablehq.com/@ersouthall/sis-model

**Comment by sdwfrost** [comment]
Incorporated into a collection, with minor edit for attribution:
[https://beta.observablehq.com/@epichef/sis-model](https://beta.observablehq.com/@epichef/sis-model)

Included in the cookbook as an iframe:
[http://epirecip.es/epicookbook/chapters/sis/js_observable](http://epirecip.es/epicookbook/chapters/sis/js_observable)

Including Observable 'properly' requires a bit more work, but am closing for now.
