### ISSUE TITLE
Observable: SIR on a configuration network

### ISSUE THREAD

**Issue by c-lack** [epirecipes/shopping-list#49]
Port of the R code
https://beta.observablehq.com/@c-lack/sir-on-a-configuration-network

**Comment by sdwfrost** [comment]
Incorporated into a collection, with minor edit for attribution:
[https://beta.observablehq.com/@epichef/sir-on-a-configuration-network](https://beta.observablehq.com/@epichef/sir-on-a-configuration-network)

Included in the cookbook as an iframe:
[http://epirecip.es/epicookbook/chapters/sircn/js_observable](http://epirecip.es/epicookbook/chapters/sircn/js_observable)
